import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/components/QueryProvider";

const lato = localFont({
  src: "../fonts/Lato-Regular.ttf",
  weight: "400",
  style: "normal",

  variable: "--font-lato",
  display: "swap",
});

const elms = localFont({
  src: "../fonts/ElmsSans-Regular.ttf",
  weight: "400",
  style: "normal",

  variable: "--font-elms",
  display: "swap",
});

export const metadata: Metadata = {
  title: "DTS - FutMX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable} ${elms.variable} antialiased`}>
        <QueryProvider>
          {/* <ClerkProvider> */}
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Toaster position="top-right" />
            <main className="max-w-[2000px] mx-auto">
              {children}
            </main>
          </ThemeProvider>
          {/* </ClerkProvider> */}
        </QueryProvider>
      </body>
    </html>
  );
}
